// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using emigest_back.Data;

#nullable disable

namespace emigest_back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517104959_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("emigest_back.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("emigest_back.Models.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Mention")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NomDelegue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumDelegue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Parcours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SalleClasse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("emigest_back.Models.EmploiDuTemps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<string>("HeureDebut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("heure_debut");

                    b.Property<string>("HeureFin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("heure_fin");

                    b.Property<string>("JourSemaine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jour_semaine");

                    b.Property<string>("Matiere")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matiere");

                    b.Property<DateTime>("MisAJourLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mis_a_jour_le");

                    b.Property<string>("NomGroupe")
                        .HasColumnType("text")
                        .HasColumnName("nom_groupe");

                    b.Property<string>("NomProfesseur")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_professeur");

                    b.Property<int>("SalleId")
                        .HasColumnType("integer")
                        .HasColumnName("salle_id");

                    b.Property<string>("Semestre")
                        .HasColumnType("text")
                        .HasColumnName("semestre");

                    b.HasKey("Id");

                    b.HasIndex("SalleId");

                    b.ToTable("emplois_du_temps");
                });

            modelBuilder.Entity("emigest_back.Models.Salle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Batiment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("batiment");

                    b.Property<int>("Capacite")
                        .HasColumnType("integer")
                        .HasColumnName("capacite");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cree_le");

                    b.Property<string>("Equipement")
                        .HasColumnType("text")
                        .HasColumnName("equipement");

                    b.Property<bool?>("EstDisponible")
                        .HasColumnType("boolean")
                        .HasColumnName("est_disponible");

                    b.Property<int>("Etage")
                        .HasColumnType("integer")
                        .HasColumnName("etage");

                    b.Property<DateTime>("MisAJourLe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mis_a_jour_le");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.ToTable("salles");
                });

            modelBuilder.Entity("emigest_back.Models.EmploiDuTemps", b =>
                {
                    b.HasOne("emigest_back.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salle");
                });
#pragma warning restore 612, 618
        }
    }
}
